### ISSUE TITLE
Vendor Country is likely wrong 

### ISSUE THREAD

**Issue by boris-moduscreate** [carwin/snyk-auto-issues-jira#1]
![Google Chrome 2022-08-10 at 17 12 17](https://user-images.githubusercontent.com/107943674/184021109-844de7e1-1f12-4eca-93ad-9081008f0a8e.png)

This could reduce people's willingness to try the app.

**Comment by carwin** [comment]
Thanks for the heads up.

**Comment by carwin** [comment]
Attempting to update this on the Atlassian side results in an error. I may need some assistance from Atlassian to resolve.
![image](https://user-images.githubusercontent.com/715967/184701921-99f5934d-4d5b-4e1f-9141-11e8208f50d8.png)

Apparently I can choose any other value except United States. As a test I chose United Kingdom and it saved without issue.

**Comment by carwin** [comment]
Was finally able to resolve this today. Closing.
